services:
  - type: web
    name: java-project-99
    runtime: docker
    repo: https://github.com/SNKiii/java-project-99
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: app-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: app-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: app-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: app-db
          property: database

databases:
  - name: app-db
    plan: free
    databaseName: app_db
    user: app_user