services:
  - type: web
    name: java-project-99
    runtime: docker
    repo: https://github.com/SNKiii/java-project-99
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: app-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: app-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: app-db
          property: password

databases:
  - name: app-db
    plan: free
    databaseName: app_db
    user: app_user