spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: java-project-99

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_for_production_please_change}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"